### PR TITLE
Add greater than/less than comparisons

### PR DESCRIPTION
**Pull request by cuducos**
Implement comparisons to be used with `|>`, as described in #1.

### CODE REVIEW

**Comment by ianmackenzie** [comment]
Looks good! Wondering about naming a bit though...first of all I think it should be `lessThan`, not `lesserThan` (https://ell.stackexchange.com/questions/820/is-it-less-than-or-lesser-than).

I also realized that since I created this issue I went and added [Quantity.lessThan](https://package.elm-lang.org/packages/ianmackenzie/elm-units/latest/Quantity#lessThan), [Quantity.greaterThan](https://package.elm-lang.org/packages/ianmackenzie/elm-units/latest/Quantity#greaterThan) to [elm-units](https://package.elm-lang.org/packages/ianmackenzie/elm-units/latest/), so for consistency I'm wondering about dropping the `is` prefix here too. An alternative might be to add `is*` versions to `elm-units` as aliases - do you think there's a significant increase in readability/explicitness with the `is` prefix?

**Comment by cuducos** [comment]
> do you think there's a significant increase in readability/explicitness with the `is` prefix?

No. I think `lessThan` (and variants) are good enough : ) Gonna change the API and update this PR!

**Comment by ianmackenzie** [comment]
Just made a couple small documentation tweaks - I think this is pretty much ready to go. (By the way, if you're not already familiar with it, [elm-doc-preview](https://github.com/dmy/elm-doc-preview) is a fantastic tool for previewing documentation during development.)

I also added an `AUTHORS` file; take a look and see if you'd like to tweak your entry at all. Once you're OK with everything I think this is ready to merge!

**Comment by cuducos** [comment]
Thanks for the tip about `elm-doc-preview` – I've been away from Elm community for a while and I've indeed missed that, pretty cool!

All the changes you've made look good to me ; )

**Comment by ianmackenzie** [comment]
Awesome, thanks! Merging =)

**Comment by ianmackenzie** [comment]
Oops - just realized the tests weren't actually exposed, so weren't getting run, and actually had a few typos! The code itself was fine, and I've fixed the tests in `master` (cba7f6328ec8b0110c1e131be9a5d1e7beca64cd). I should have caught that - `elm-test` requires all tests to be explicitly listed in the `exposing` line. Anyways, nothing to do, just something to keep in mind =)

**Pull request merged**
